"""Worker job for reviewing essays."""
from sqlalchemy.orm import Session
from src.db import SessionLocal
from src.models.essay import Essay
from src.models.essay_version import EssayVersion
from src.models.essay_review import EssayReview
from datetime import datetime
import json


def review_essay(essay_id: str, attempt: int = 1):
    """Review an essay using LLM (placeholder).
    
    This is a placeholder for the actual worker implementation.
    In production, this would be called by Celery/RQ and use an LLM.
    
    IMPORTANT: This function provides FEEDBACK ONLY, never rewrites essays.
    
    Args:
        essay_id: Essay UUID as string
        attempt: Attempt number for retries
    """
    db = SessionLocal()
    try:
        from uuid import UUID
        essay_uuid = UUID(essay_id)
        
        # Fetch essay and latest version
        essay = db.query(Essay).filter(Essay.id == essay_uuid).first()
        if not essay:
            print(f"Essay {essay_id} not found")
            return
        
        latest_version = db.query(EssayVersion).filter(
            EssayVersion.essay_id == essay_uuid
        ).order_by(EssayVersion.version_number.desc()).first()
        
        if not latest_version:
            print(f"Essay {essay_id} has no content")
            return
        
        # TODO: Call LLM for structured feedback
        # The prompt must explicitly state:
        # - Provide feedback and suggestions only
        # - Do NOT rewrite the essay
        # - Do NOT generate improved versions
        # - Focus on strengths, weaknesses, and areas for improvement
        
        # Placeholder feedback
        review = EssayReview(
            essay_id=essay_uuid,
            essay_version_id=latest_version.id,
            overall_score=7.5,
            clarity_score=8.0,
            structure_score=7.0,
            content_score=7.5,
            grammar_score=8.0,
            strengths="Clear introduction, good use of examples.",
            weaknesses="Could strengthen the conclusion, some transitions need work.",
            suggestions="Consider adding more specific examples in the middle section.",
            detailed_feedback="This is a placeholder for detailed feedback. In production, this would be generated by an LLM with strict instructions to provide feedback only, never to rewrite.",
        )
        
        db.add(review)
        db.commit()
        print(f"Essay {essay_id} reviewed successfully")
        
    except Exception as e:
        print(f"Error reviewing essay {essay_id}: {e}")
        db.rollback()
    finally:
        db.close()

